### ISSUE TITLE
Flutter 配置 Dart Linter 语法风格校验

### ISSUE THREAD

**Issue by lanten** [lanten/lanten.github.io#15]
## 添加配置文件

在项目根目录添加文件 `analysis_options.yaml` 内容如下

```yaml
# 导入 pedantic 默认配置, 这不是必须的
include: package:pedantic/analysis_options.yaml

analyzer:
  errors:
    slash_for_doc_comments: ignore # 忽略 `/** */` 风格注释警告

linter:
  # 添加规则
  rules:
    # - avoid_empty_else
    # - ...

```

## 相关参考
- [规则列表](https://dart-lang.github.io/linter/lints/)
- [pedantic](https://pub.dev/packages/pedantic)
- [Linter for Dart](https://github.com/dart-lang/linter)
